baseURL = "https://isanchez.net/"
languageCode = "en-gb"
title = "Ivan Sanchez"
theme = "hermit"
googleAnalytics = ""
publishDir = "s4nchez.github.io"

pygmentsCodefences  = true
pygmentsUseClasses  = true
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."

[author]
  name = "Ivan Sanchez"

[params]
  dateform        = "2 Jan 2006"
  dateformShort   = "2 Jan"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"

  themeColor = "#494f5c"

#  homeSubtitle = ""
  footerCopyright = ' &#183; <a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
  justifyContent = false  # Set "text-align: justify" to `.content`.
  relatedPosts = false  # Add a related content section to all single posts page
  code_copy_button = true # Turn on/off the code-copy-button for code-fields

 [[params.social]]
    name = "twitter"
    url = "https://twitter.com/s4nchez"

  [[params.social]]
    name = "github"
    url = "https://github.com/s4nchez"

[menu]

  [[menu.main]]
    name = "Blog"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About"
    url = "about/"
    weight = 20